[tool.poetry]
name = "influencer-nexus"
version = "0.1.0"
description = "A web application designed to connect sponsors and influencers for seamless campaign management."
authors = ["Vagadeeshwar G <21f1005494@ds.study.iitm.ac.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
