[tool.poetry]
name = "influencer-nexus"
version = "0.1.0"
description = "A web application designed to connect sponsors and influencers for seamless campaign management."
authors = ["Vagadeeshwar G <vagadeeshwarganesan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
